server:
        host: 'localhost'
        port: 3000
twitch:
        server: 'irc.chat.twitch.tv'
        port: 6667
        client_id: 'client_id'
        client_secret: 'client_secret'
        name: 'pertybot'
        channel: '#your_channel_name'