FROM python:3.11.4

ADD bin/ bin/
ADD spotify/ spotify/
# ADD .env .env
ADD bot.py bot.py
# RUN ls --recursive


# ARG SPOTIFY_CLIENT_ID
# ARG SPOTIFY_CLIENT_SECRET
# ARG SPOTIFY_CALLBACK_URI
# ARG SPOTIFY_AUTHORIZATION_TOKEN
# ARG SPOTIFY_ACCESS_TOKEN
# ARG SPOTIFY_REFRESH_TOKEN
# ARG SPOTIFY_USER_ID

# ARG TMI_TOKEN
# ARG CLIENT_ID
# ARG REFRESH_TOKEN
# ARG BOT_NICK
# ARG BOT_PREFIX
# ARG CHANNEL


# ENV TMI_TOKEN=$TMI_TOKEN
# ENV CLIENT_ID=$CLIENT_ID
# ENV REFRESH_TOKEN=$REFRESH_TOKEN
# ENV BOT_NICK=$BOT_NICK
# ENV BOT_PREFIX=$BOT_PREFIX
# ENV CHANNEL=$CHANNEL



# ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
# ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
# ENV SPOTIFY_CALLBACK_URI=$SPOTIFY_CALLBACK_URI
# ENV SPOTIFY_AUTHORIZATION_TOKEN=$SPOTIFY_AUTHORIZATION_TOKEN
# ENV SPOTIFY_ACCESS_TOKEN=$SPOTIFY_ACCESS_TOKEN
# ENV SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN
# ENV SPOTIFY_USER_ID=$SPOTIFY_USER_ID


#############################

# ARG TMI_TOKEN_ARG
# ARG CLIENT_ID_ARG
# ARG REFRESH_TOKEN_ARG
# ARG BOT_NICK_ARG
# ARG BOT_PREFIX_ARG
# ARG CHANNEL_ARG

# ENV TMI_TOKEN=$TMI_TOKEN_ARG
# ENV CLIENT_ID=$CLIENT_ID_ARG
# ENV REFRESH_TOKEN=$REFRESH_TOKEN_ARG
# ENV BOT_NICK=$BOT_NICK_ARG
# ENV BOT_PREFIX=$BOT_PREFIX_ARG
# ENV CHANNEL=$CHANNEL_ARG

# ARG SPOTIFY_CLIENT_ID_ARG
# ARG SPOTIFY_CLIENT_SECRET_ARG
# ARG SPOTIFY_CALLBACK_URI_ARG
# ARG SPOTIFY_AUTHORIZATION_TOKEN_ARG
# ARG SPOTIFY_ACCESS_TOKEN_ARG
# ARG SPOTIFY_REFRESH_TOKEN_ARG
# ARG SPOTIFY_USER_ID_ARG

# ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID_ARG
# ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET_ARG
# ENV SPOTIFY_CALLBACK_URI=$SPOTIFY_CALLBACK_URI_ARG
# ENV SPOTIFY_AUTHORIZATION_TOKEN=$SPOTIFY_AUTHORIZATION_TOKEN_ARG
# ENV SPOTIFY_ACCESS_TOKEN=$SPOTIFY_ACCESS_TOKEN_ARG
# ENV SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN
# ENV SPOTIFY_USER_ID=$SPOTIFY_USER_ID




RUN pip install requests twitchio
RUN chmod +x bot.py bin/start.sh

#CMD [ "python", "./bot.py" ]
ENTRYPOINT ["bash", "bin/start.sh"]
