name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Package Registry
      env:
        ZDOCKER_PASSWORD: ${{ secrets.ZDOCKER_PASSWORD }}
        ZDOCKER_USERNAME: ${{ vars.ZDOCKER_USERNAME }}
        ZDOCKER_URL: ${{ vars.ZDOCKER_URL }}
      run: echo $ZDOCKER_PASSWORD | docker login $ZDOCKER_URL -u $ZDOCKER_USERNAME --password-stdin
    - name: Build the Docker image
      env:
        SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
        ENV_FILE: ${{ secrets.ENV_FILE }}
        TOKEN_CODE_YML: ${{ secrets.TOKEN_CODE_YML }}
      run: |
        echo $SPOTIFY_TOKEN > .token.txt
        echo $ENV_FILE > .env
        echo $TOKEN_CODE_YML > twitch/code.yml
        echo $TOKEN_CONFIG_YML > twitch/config.yml
        
        docker build . --file Dockerfile -t zetabotti
        docker tag zetabotti:latest zdocker.zaikki.com/zetabotti:latest
        docker push zdocker.zaikki.com/zetabotti:latest

    # - name: Read template from file
    #   id: template
    #   uses: traversals-analytics-and-intelligence/file-reader-action@master
    #   with:
    #     file: .token.txt

    # - name: Get the template output
    #   run: echo "${{ steps.template.outputs.content }}"
