name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Package Registry
      env:
        ZDOCKER_PASSWORD: ${{ secrets.ZDOCKER_PASSWORD }}
        ZDOCKER_USERNAME: ${{ vars.ZDOCKER_USERNAME }}
        ZDOCKER_URL: ${{ vars.ZDOCKER_URL }}
      run: echo $ZDOCKER_PASSWORD | docker login $ZDOCKER_URL -u $ZDOCKER_USERNAME --password-stdin
    - name: Build the Docker image
      env:
        SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
        ENV_FILE: ${{ secrets.ENV_FILE }}
        TOKEN_CODE_JSON: ${{ secrets.TOKEN_CODE_JSON }}
        TOKEN_CONFIG_JSON: ${{ secrets.TOKEN_CONFIG_JSON }}
      run: |
        echo $SPOTIFY_TOKEN > .token.json
        echo $ENV_FILE > .env
        echo $TOKEN_CODE_JSON > twitch/code.json
        echo $TOKEN_CONFIG_JSON > twitch/config.json
        
        docker build . --file Dockerfile -t zetabotti
        docker tag zetabotti:latest zdocker.zaikki.com/zetabotti:latest
        docker push zdocker.zaikki.com/zetabotti:latest

    - name: Trigger Portainer webhook
      run: |
        curl -X POST "https://portainer.zaikki.com/api/stacks/webhooks/638e6967-ef77-4906-8af8-236800621360?tag=latest"
