name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
      run: |
        echo $SPOTIFY_TOKEN > .token.txt
        echo .token.txt
        # docker build . --file Dockerfile -t zetabotti
        # docker tag zetabotti:latest zdocker.zaikki.com/zetabotti:latest
        # docker push zdocker.zaikki.com/zetabotti:latest
